bassignment/account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout, name='logout'),
    path('signup/', signup_view, name='signup')
]

bassignment/bassignment/urls.py
from django.contrib import admin
from django.urls import path, include
import blog.views 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog.views.home, name = 'home'),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

bassignment/blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('<int:id>', detail, name = 'detail'),
    path('new/', new, name ='new'),
    path('new_with_django_form/', new_with_django_form, name = 'new_with_django_form'),
    path('create/', create, name = 'create'),
    path('create_with_django_form/', create_with_django_form, name = 'create_with_django_form'),
    path('update/<int:id>', update, name = 'update'),
    path('delete/<int:id>', delete, name = "delete"),
    path('create_comments/<int:id>', create_comments, name="create_comments"),
    path('delete_comments/<int:blog_id>/<int:comment_id>', delete_comments, name = "delete_comments"),
]

bassignment/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class CustomUser(AbstractUser):
    nickname = models.CharField(max_length=100)
    university = models.CharField(max_length=50)
    tier = models.CharField(max_length=200)

bassignment/blog/models.py
from pickle import TRUE
from django.db import models
from django.conf import settings
from account.models import CustomUser

# Create your models here.

class Blog(models.Model):
    user = models.ForeignKey(CustomUser, null=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    writer = models.CharField(max_length=10)
    pub_date = models.DateTimeField()
    body = models.TextField(null=TRUE)
    image = models.ImageField(upload_to="blog/", blank=True, null=True)

    def __str__(self):
        return self.title
    
    def summary(self):
        return self.body[:150]

class Comment(models.Model):
    post = models.ForeignKey(Blog, null=True, blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank = True, on_delete = models.CASCADE)
    content = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

bassignment/account/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class SignupForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password1', 'password2', 'nickname', 'university', 'tier']

bassignment/blog/forms.py
from django import forms
from .models import Blog, Comment

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'writer', 'body', 'image']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]

bassignment/account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib import auth

from .forms import SignupForm

# Create your views here.

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = auth.authenticate(
                request=request,
                username=username,
                password=password
            )
            if user is not None:
                auth.login(request,user)
                return redirect('home')
        
        return redirect('account:login')
        
    else:
            form = AuthenticationForm()
            return render(request, 'login.html', {'form': form})

def logout(request):
    auth.logout(request)
    return redirect('home')

def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth.login(request, user)
            return redirect('home')
        return redirect('account:signup')
    
    else:
        form = SignupForm()
        return render(request, 'signup.html', {'form':form})

bassignment/blog/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone

from .models import Blog, Comment
from .forms import BlogForm, CommentForm
from django.core.paginator import Paginator

# Create your views here.

def home(request):
    blogs = Blog.objects.order_by('-pub_date')

    query = request.GET.get('query')
    if query: 
        blogs = Blog.objects.filter(title__contains=query)
    
    paginator = Paginator(blogs, 3)
    page = request.GET.get('page')
    paginated_blogs = paginator.get_page(page)
    return render (request, 'home.html', {'blogs': paginated_blogs})

def detail(request, id):
    blog = get_object_or_404(Blog, pk = id)
    comment_form = CommentForm()
    comments = Comment.objects.filter(post_id=id).order_by('-created_at')
    return render (request, 'detail.html', {'blog': blog, "comment_form": comment_form, "comments": comments})

def new(request):
    return render(request, 'new.html')

def new_with_django_form(request):
    form = BlogForm()
    return render(request, 'new_with_django_form.html', {'form': form})

def create(request):
    new_blog = Blog()
    new_blog.title = request.POST['title']
    new_blog.writer = request.POST['writer']
    new_blog.body = request.POST['body']
    new_blog.image = request.FILES['image']
    new_blog.pub_date = timezone.now()
    new_blog.save()
    return redirect('blog:detail', new_blog.id)

def create_with_django_form(request):
    form = BlogForm(request.POST, request.FILES)
    if form.is_valid():
        new_blog = form.save(commit=False)
        new_blog.pub_date = timezone.now()
        if request.user.is_authenticated:
            new_blog.user = request.user
        new_blog.save()
        return redirect('blog:detail', new_blog.id)
    return redirect('home')    

def update(request, id):
    blog = Blog.objects.get(id = id)
    if request.method == "POST":
        blog.title = request.POST["title"]
        blog.body = request.POST["body"]
        blog.save()
        return redirect('blog:detail', blog.id)    
    return render(request, 'update.html', {"blog" : blog})

def delete(request, id):
    blog = Blog.objects.get(id=id)
    blog.delete()
    return redirect("home")

def create_comments(request, id):
    form = CommentForm(request.POST)
    if form.is_valid():
        c_form = form.save(commit=False)
        c_form.post = get_object_or_404(Blog, pk=id)
        if request.user.is_authenticated:
            c_form.user = request.user
        c_form.save()
    return redirect('blog:detail', id)

def delete_comments(request, blog_id, comment_id):
    comment = Comment.objects.get(pk = comment_id)
    if request.user.is_authenticated:
        comment.delete()
    return redirect('blog:detail', blog_id)

bassignment/account/templates/login.html
{% extends 'base.html' %}

{% block content %}

<h1>LOGIN</h1>
</br>
<form action="{% url 'account:login' %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">로그인</button>
</form>

{% endblock %}

bassignment/account/templates/signup.html
{% extends 'base.html' %}

{% block content %}

<h1>JOIN US!</h1>
<form action="{% url 'account:signup' %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">Join</button>
</form>
{% endblock %}

bassignment/bassignment/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gamja+Flower&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poor+Story&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>Blog</title>
    <style>

      header {
        text-align: left;
        margin-top: 20px;
        margin-bottom: 20px;
      }
      body {
        text-align: center;
        background-image: url('https://i.pinimg.com/originals/df/4e/bb/df4ebbdd533ff1c193ca126df329a498.png');
        background-size: 80%;
        font-family: 'Poor Story', cursive;
        }
      footer{
        width: 100%;
        height: 80px;
        border-top: solid 1px black;
        position: absolute;
        left: 0;
        bottom: 0;
        width: 100%;
        padding-top: 20px;
        background-color: whitesmoke;
        margin: 0;
        font-family: 'Gamja Flower', cursive;
      }
      .passages {
        border: solid 3px black;
        margin-bottom: 30px;
        text-align: left;   
        border-radius: 15px;
        background-color: mintcream;
        font-family: 'Gamja Flower', cursive;
      }
      .comments {
        text-align: center;
        font-size: 18px;
        font-family: 'Gamja Flower', cursive;
      }
      .container {
        font-size: 18px;
      }
      
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{%url 'home' %}"><img src = "{% static 'challenger.jpg' %}" alt = "" style = "max-width: 60px; max-height: 60px;"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'blog:new_with_django_form'%}">글 작성하기</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://lolchess.gg/">LOLCHESS.GG 바로가기</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">{{user.tier}}에 서식하는 {{user.university}}생 {{user.nickname}}님 안녕하세요!</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:logout' %}" tabindex="-1" aria-disabled="true">로그아웃</a> 
            </li>

            {% else %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:login' %}" tabindex="-1" aria-disabled="true">로그인</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:signup' %}" tabindex="-1" aria-disabled="true">회원가입</a>
            </li>
            {% endif %}
          </ul>
          <form class="d-flex" action="{% url 'home' %}">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name = "query">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    <div class = "container">
        {% block content %}
        {% endblock %}
    </div>
    <div class="footer">
      <footer>
        {% if user.is_authenticated %}
        <p> <img src = "{% static 'icon.jpg' %}" alt = "" style = "max-width: 50px; max-height: 50px;">&nbsp; {{user.nickname}}님의 공략을 적어주세요!</p>
        {% else %}
        <p>  <img src = "{% static 'icon.jpg' %}" alt = "" style = "max-width: 50px; max-height: 50px;">&nbsp;<a href="{% url 'account:signup' %}"> 회원가입</a> 후 이용해주세요!</p>
        {% endif %}
      </footer>
    <br>
  </body>
</html>

bassignment/blog/templates/detail.html
{% extends 'base.html' %}
    {% block content %}
    <div class="container">
      </br>
      <h4>{{ blog.title }}</h4>
      <p>{{ blog.pub_date }}</p>
      {% if blog.image %}
      <p><img src="{{blog.image.url}}" alt="" style = "max-width: 100%; max-height: 100%;"></p>
      {% endif %}
      <p>{{ blog.body }}</p>
      <a href="{% url 'blog:update' blog.id %}">수정하기</a>
      <a href="{% url 'blog:delete' blog.id %}">삭제하기</a>
      <a href="{% url 'home' %}">홈으로</a>
    </div>
    
    <div class="comments">
      <hr>
      {% if comments %}
      <p>총 {{comments | length }} 개의 댓글</p>
      {% endif %}
      <!--read-->
      
      <ul>
        {% for comment in comments %}
          {% if request.user == comment.user %}
          <li>
            <p>{{ user.nickname }} | {{ comment.created_at}}</p>
            <p>{{ comment.content }}</p>
            <!--delete-->
            {% if user == comment.user %}
              <form action="{% url 'blog:delete_comments' blog.id comment.id %}" method="POST" class="d-inline">
                {% csrf_token %}
                <input type="submit" value="삭제">
              </form>
            {% endif %}
          {% else %}
            <li>
              <p> AnonymousUser | {{ comment.created_at}}</p>
              <p>{{ comment.content }}</p>
              <!--delete-->
              {% if user == comment.user %}
                <form action="{% url 'blog:delete_comments' blog.id comment.id %}" method="POST" class="d-inline">
                  {% csrf_token %}
                  <input type="submit" value="삭제">
                </form>
              {% endif %}
            {% endif %}
            </li>
        {% empty %}
          <p>첫 댓글을 써주세요!</p>
        {% endfor %}
      </ul>
      
      <!--create-->
      {% if request.user.is_authenticated %}
        <form action="{% url 'blog:create_comments' blog.id %}" method="POST">
          {% csrf_token %}
          <span>{{ user.nickname }} | </span>
          {{ comment_form }} </br>
          </br>
          <input type="submit" value = "댓글 작성">
        </form>
      {% else %}
        <form action="{% url 'blog:create_comments' blog.id %}" method="POST">
          {% csrf_token %}
          <span> AnonymousUser | </span>
          {{ comment_form }} </br>
          </br>
          <input type="submit" value = "댓글 작성">
        </form>
      {% endif %}
      
      <!--생략-->
    </div>

    {% endblock %}

bassignment/blog/templates/home.html
{% extends 'base.html' %}

    {% block content %}
      <header>
        <h2> 전체 글보기  </h2>
      </header>
      
      <div class = "container">
      {% for blog in blogs%}
        <div class = "passages">
          <h4><b>&nbsp;{{ blog.title }}</b></h4>
          &nbsp;<b>소환사명:</b> {{ blog.writer}}</br>
          &nbsp;<b>작성시간:</b> {{ blog.pub_date}}</br>
          &nbsp;<b>내용:</b> {{ blog.summary }}</br>
          <a href="{% url 'blog:detail' blog.id %}" style="color: lightslategrey">&nbsp;...more</a>
        </div>
       
        
      {%endfor %}
      </div>

      <div class="paginator">
        {% if blogs.has_previous %}
        <a href="?page=1" style="color: lightslategrey">처음</a>
        <a href="?page={{blogs.previous_page_number}}" style="color: lightslategrey">이전</a>
        {% endif %}
        <span>{{blogs.number}}</span>
        <span>of</span>
        <span>{{blogs.paginator.num_pages}}</span>
        {% if blogs.has_next %}
        <a href="?page={{blogs.next_page_number}}" style="color: lightslategrey">다음</a>
        <a href="?page={{blogs.paginator.num_pages}}" style="color: lightslategrey">마지막</a>
        {% endif %}
      </div>
    
    {% endblock %}

bassignment/blog/templates/new.html
{% extends 'base.html' %}
{% block content %}
    <h1>새로운 글</h1>
    <form action="{% url 'blog:create_with_django_form' %}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        <p>제목: <input type="text" name="title"></p>
        <p>작성자: <input type="text" name="writer"></p>
        <p>사진: <input type="file" name="image" /></p>
        본문: <br><textarea name="body" id="" cols="30" rows="10"></textarea><br>
        <button type='submit'>작성하기</button>
    </form>
{% endblock %}

bassignment/blog/templates/new_with_django_form.html

{% extends 'base.html' %}

{% block content %}
</br>
<h1>새로운 글</h1>
<form action="{%url 'blog:create_with_django_form'%}" method="post" enctype="multipart/form-data">
    {%csrf_token%}

    {{form.as_p}}
    <button type='submit'>작성하기</button>
</form>
{% endblock %}

bassignment/blog/templates/update.html
{% extends 'base.html' %}
    {% block content %}
    </br>
    <h4> 글 수정하기 </h4>

    <form action="{% url 'blog:update' blog.id %}" method = "POST">
        {% csrf_token %}
        <h4>제목: </h4>
        <input type="text" name="title" value={{blog.title}}>
        <br>
        <br>
        <h4>본문: </h4>
        <textarea name="body" cols="30" rows="10">{{blog.body}}</textarea><br><br>
        <input type="submit" value="완료">
    </form>
    {% endblock %}